### ISSUE TITLE
Noriben will crash with "--pml" option

### ISSUE THREAD

**Issue by mnrkbys** [Rurik/Noriben#21]
I found a issue of Version 1.8.2.
Noriben will crash with the following message, when I specify "--pml".
>Traceback (most recent call last):
>  File "Noriben.py", line 1488, in <module>
>    main()
>  File "Noriben.py", line 1365, in main
>    with open(timeline_file, newline='', encoding='utf-8') as f:
>FileNotFoundError: [Errno 2] No such file or directory: 'Noriben_06_Jul_18__12_31_034122_timeline.csv'

I found a bug around 1364 line.
>             print('[*] Saving timeline to: {}'.format(timeline_file))
>            # codecs.open(timeline_file, 'w', 'utf-8').write('\r\n'.join(timeline))
>            with open(timeline_file, newline='', encoding='utf-8') as f:
>                writer = csv.writer(f)
>                writer.writerows(timeline)

I modified it such as following. It seems to work.
>            print('[*] Saving timeline to: {}'.format(timeline_file))
>            codecs.open(timeline_file, 'w', 'utf-8').write('\r\n'.join(timeline))
>            # with open(timeline_file, newline='', encoding='utf-8') as f:
>                # writer = csv.writer(f)
>                # writer.writerows(timeline)

**Comment by Rurik** [comment]
Thank you, very much appreciated.

Can you confirm that you are on 1.8.2? I had run across that bug recently and put a tiny fix into 1.8.2 to fix it, here:

https://github.com/Rurik/Noriben/commit/84b3c13cd093dbcb474421749b00c93cc5c70ddf#diff-bf0696a9ab04ef94dda0bdda3c4ffceb

The bug was that I left out the 'w' from the open() on line , which made the code try to read an existing file instead of create a new one. From your error message, it appears your code is 1.8.1?

**Comment by mnrkbys** [comment]
I'm so sorry, I have misunderstood.
I was checking the version 1.8.1.
Please close this issue.

**Comment by Rurik** [comment]
Not a problem at all. It was a bad bug that I put in; I'm sorry for that. Thanks for reporting!
