### ISSUE TITLE
Registry lenght exceeded

### ISSUE THREAD

**Issue by Feldunost** [Rurik/Noriben#29]
Hello,

Currently encountered this issue on Win 10 x64.
The command Noriben.py -p file.pml doesn't help with this problem.

I guess the registry lenght changed quite a lot since Win 7.
This only crashes after .pml generation which means the file is stills saved but not in .txt format.

> --===[ Noriben v1.8.3
> --===[ Brian Baskin [brian@thebaskins.com / @bbaskin]
> [*] Using filter file: ProcmonConfiguration.PMC
> Traceback (most recent call last):
>   File "Noriben.py", line 1046, in parse_csv
>     if int(reg_length):
> ValueError: invalid literal for int() with base 10: '2\xa0691'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "Noriben.py", line 1494, in <module>
>     main()
>   File "Noriben.py", line 1364, in main
>     parse_csv(csv_file, report, timeline)
>   File "Noriben.py", line 1063, in parse_csv
>     error_output.append(original_line.strip())
> AttributeError: 'list' object has no attribute 'strip'

**Comment by Rurik** [comment]
My apologies for the delay and it's a hope that you may still have this data available.

Do you happen to have the PML, or the converted CSV, for this runtime? I've never seen a registry length of that size before. While I can add some error handling around it, I want to ensure that it's not removing or breaking critical data that should go in the report.

**Comment by Feldunost** [comment]
Thats actually because there was a malware analysis. The executable was writing in registry with very long values and I am not even sure if it was an UTF8 name ...

I will regenerate the .pml on the fly tomorrow.

**Comment by Feldunost** [comment]
.pml file sent through mail.

**Comment by Feldunost** [comment]
Hello Rurik,
Same problem on clean machine.
A short .pml file will be sent.
Regards.

**Comment by darioplatania** [comment]
Hello, I solved by changing casting to line 1046, from int to float.
Regards.

**Comment by Feldunost** [comment]
This is a solution, indeed, thing is to verify if that doesn't make problems afterwards.
Going under testing since few days on it, to check out, I can't tell if that's 100% working for now.

**Comment by Rurik** [comment]
Thanks for all this. My travel season is almost over (two more weeks) and I'll have a chance to catch up and review. Changing to float would fix this, but I'm hesitant on that. It'll work for a quick fix for now though.

**Comment by darioplatania** [comment]
Exactly, it's just a temporary solution. Keep us updated on any corrections. Thank's for your job!

**Comment by Feldunost** [comment]
It still has some bugs.

Traceback (most recent call last):
  File "Noriben.py", line 1046, in parse_csv
    if float(reg_length):
ValueError: could not convert string to float: '4\xa0671'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Noriben.py", line 1494, in <module>
    main()
  File "Noriben.py", line 1481, in main
    parse_csv(csv_file, report, timeline)
  File "Noriben.py", line 1063, in parse_csv
    error_output.append(original_line.strip())
AttributeError: 'list' object has no attribute 'strip'

[Noriben.zip](https://github.com/Rurik/Noriben/files/3305909/Noriben.zip)

**Comment by Rurik** [comment]
This is under deeper review now. Earlier troubleshooting failed because, well, it didn't fail here on those files. Putting in some checks and tests to make it fail and then review more.

**Comment by Rurik** [comment]
Okay, two issues in play here. I'll fix the latter one easily (AttributeError: 'list' object has no attribute 'strip') first, which would help in the troubleshooting of the former issue. This error is due to the use of the CSV library to pull each line of data. This was an error introduced due to the change from a manual CSV parser to the CSV library. CSV.reader reads in a line of text and automatically converts it to a list.

The former is a unicode issue of 0xc0a0 being translated to UTF-8 \x000A (non-break space / NBSP). It's made frustrating here because the CSV.reader is set to read as UTF-8 but it's not doing so.

**Comment by Rurik** [comment]
Unfortunate news is that due to a VMWare issue, all of the work done to correct these problems was lost. As I work off a Mac, all coding/testing is done in a Windows VM. I'm saddened by this loss, and I know others are frustrated by the lack of release. I will work towards an MVP for the immediate errors and then try to re-tackle the long-term problems when I gain my motivation again.

**Comment by Rurik** [comment]
The float() change was committed. I've been unable to do a proper re-write (again) of the code to fix. I'm going to keep this issue open until that time can occur. But, for now, this immediately error should be fixed.

**Comment by Rurik** [comment]
This issue is now resolved by 1.8.5 and 1.8.6 releases.
Thank you everyone for the help!
