### ISSUE TITLE
SSL error connecting to VirusTotal

### ISSUE THREAD

**Issue by oasec1** [Rurik/Noriben#6]
Besides turning of the VirusTotal functionality, any thoughts on how to rectify this?

C:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:90: Insecur
ePlatformWarning: A true SSLContext object is not available. This prevents urlli
b3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/securit
y.html#insecureplatformwarning.

Thanks
Robert

**Comment by Rurik** [comment]
This is a warning that pops up in certain versions of Python due to older libraries with outdated SSL. It doesn't stop Noriben from running, and VT should still connect.

To fix, you'll need to update your local libs to work with the HTTP library that Noriben uses ("Requests"). This can be done manually, or by upgrading to the latest Python.

For manual steps, use:
pip install requests[security]

For more on this error:
http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package
