### ISSUE TITLE
[!] Python module "requests" not found. Internet functionality is now disabled.

### ISSUE THREAD

**Issue by sanssg** [Rurik/Noriben#7]
There is this error:
[!] Python module "requests" not found. Internet functionality is now disabled.
--===[ Noriben v1.6.3 ]===--
--===[    @bbaskin    ]===--

However, running pip3 install requests gives:
Requirement already satisfied (use --upgrade to upgrade): requests in c:\program files (x86)\python35-32\lib\site-packages\requests-2.9.1-py3.5.egg

Thanks.

**Comment by Rurik** [comment]
Hi!

Unfortunately the way that Noriben calls requests is a standard import:
    import requests

That means there's an issue with how pip installed on your end. However, this is common, and occurred for me as well. The issue is common if you have multiple versions of Python and used 'pip' at any time. 

For me, I was able to resolve this by uninstalling requests with pip and reinstalling with pip3. I don't know if this would directly help you, though:

pip uninstall requests
pip3 uninstall requests
pip3 install requests

Unfortunately, it's an issue outside of Noriben, but I'll be happy to try and troubleshoot.

**Comment by sanssg** [comment]
Thanks, this helped.
